global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-alerts'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'telegram-alerts'
    webhook_configs:
      - url: 'http://alertmanager-bot:8080'
